---
services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./docs:/docs
    ports:
      - 3001:3001
    restart: unless-stopped
    labels: 
      tsdproxy.enable: true
      tsdproxy.scheme: https
      tsdproxy.tlsvalidate: false
      tsdproxy.container_port: "3001"
